MONGODB_HOST: mongodb-{{ env }}.tirusatrapu.fun
REDIS_HOST: redis-{{ env }}.tirusatrapu.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.tirusatrapu.fun
USER_HOST: user.backend-alb-{{ env }}.tirusatrapu.fun
CART_HOST: cart.backend-alb-{{ env }}.tirusatrapu.fun
MYSQL_HOST: mysql-{{ env }}.tirusatrapu.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.tirusatrapu.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.tirusatrapu.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.tirusatrapu.fun